<?php

/**
 * @wordpress-plugin
 * Plugin Name:       Kntnt Fix Colon in Fragments of Relative URLs
 * Plugin URI:        https://www.kntnt.com/
 * Description:       Replaces colon with dash before saving content to database.
 * Version:           1.0.0
 * Author:            Thomas Barregren
 * Author URI:        https://www.kntnt.com/
 * License:           GPL-3.0+
 * License URI:       http://www.gnu.org/licenses/gpl-3.0.txt
 */


defined('ABSPATH') || die;

/*
 * Colon is allowed in the fragment part of a URI according to RFC 3986
 * and is allowed in `id` and `name` in both HTML4 and HTML5. Despite these
 * facts, WordPress removes everything up to and including the colon when
 * a colon is used in a fragment of a relative or a protocol-relative URL.
 * An example when this cause problem is when HTML generated by Markdown Extra
 * is used, since colon is used in fragments to both link to the footnote
 * (e.g. `#fn:1`) and link back (e.g. `#fnref:1`). Thus the need for this
 * "hack" which replace colon with a dash in `id` and `name` attributes, and
 * in `href` attributes that are relative (i.e. not starting with `http://`,
 * `https://`. This is done before KSES runs and the post content is saved
 * to the database.
 */
add_filter('content_save_pre', function ($content) {
    return preg_replace_callback( '/((?:id|name)\s*?=\s*?\\\\[\'"]|href\s*?=\s*?\\\\[\'"](?!https?:\/\/)(?:[^\'"])*?#)([^\\\\]*?:(?:[^\\\\])*?)(\\\\[\'"])/', function ($matches) {
        return $matches[1] . strtr($matches[2], ':', '-') . $matches[3];
    }, $content);
}, 9);
